/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QrRouteImport } from './routes/qr'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/$postId',
  path: '/community/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/collaborate': typeof CollaborateRoute
  '/dashboard': typeof DashboardRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/collaborate': typeof CollaborateRoute
  '/dashboard': typeof DashboardRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/community': typeof CommunityIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/collaborate': typeof CollaborateRoute
  '/dashboard': typeof DashboardRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/collaborate'
    | '/dashboard'
    | '/mentor'
    | '/onboarding'
    | '/profile'
    | '/qr'
    | '/community/$postId'
    | '/learn/$slug'
    | '/community/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/collaborate'
    | '/dashboard'
    | '/mentor'
    | '/onboarding'
    | '/profile'
    | '/qr'
    | '/community/$postId'
    | '/learn/$slug'
    | '/community'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/collaborate'
    | '/dashboard'
    | '/mentor'
    | '/onboarding'
    | '/profile'
    | '/qr'
    | '/community/$postId'
    | '/learn/$slug'
    | '/community/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CollaborateRoute: typeof CollaborateRoute
  DashboardRoute: typeof DashboardRoute
  MentorRoute: typeof MentorRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  QrRoute: typeof QrRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  LearnSlugRoute: typeof LearnSlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/community/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CollaborateRoute: CollaborateRoute,
  DashboardRoute: DashboardRoute,
  MentorRoute: MentorRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  QrRoute: QrRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
  LearnSlugRoute: LearnSlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
